// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/alwatan-home/Current.tsx": () => import("../components/mockups/alwatan-home/Current.tsx"),
  "./components/mockups/alwatan-home/VariantA.tsx": () => import("../components/mockups/alwatan-home/VariantA.tsx"),
  "./components/mockups/alwatan-home/VariantB.tsx": () => import("../components/mockups/alwatan-home/VariantB.tsx")
};
